"""initial migration

Revision ID: 027327479095
Revises: 
Create Date: 2017-07-27 11:53:31.274000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027327479095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('edit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'edit_time')
    # ### end Alembic commands ###
